### ISSUE TITLE
"wrong number of arguments" error with stympy/faker v1.9.0+

### ISSUE THREAD

**Issue by rbf** [denvazh/faker_japanese#4]
# Error Description

The gem seems incompatible with `faker` v1.9.0+. With the following versions defined in the `Gemfile`:

```ruby
gem 'faker',          '1.9.1'
gem 'faker_japanese', '0.2.4'
```

loading the application fails with the following error:

```
/usr/local/rvm/gems/ruby-2.5.1/gems/bundler-1.16.3/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the
 gem 'faker_japanese'. (Bundler::GemRequireError)
Gem Load Error is: wrong number of arguments (given 1, expected 0)
Backtrace for gem load error is:
/usr/local/rvm/gems/ruby-2.5.1/gems/faker_japanese-0.2.4/lib/faker_japanese.rb:27:in `initialize'
```

# Cause

This seems due to a new `Faker::String` class created in version 1.9.0 of `faker`:

https://github.com/stympy/faker/compare/v1.8.7...v1.9.0#diff-606ca7ead800c03c3025f08d2afca96d

And by chance, the `Kanji` class in the `lib/faker_japanese.rb` module inherits from `String` but within the `Faker` module. Therefore `super` in line 27 refers now to `Faker::String` instead of ruby's `String`.

https://github.com/denvazh/faker_japanese/blob/8ab30ea2d2453994124c810da43eee9da7ce1fc9/lib/faker_japanese.rb#L12-L32

# Solution

Refer to ruby's `String` class, e.g. by prefixing the class name with `::`:

```diff
+   class Kanji < ::String
-   class Kanji < String
```
in following line:

https://github.com/denvazh/faker_japanese/blob/8ab30ea2d2453994124c810da43eee9da7ce1fc9/lib/faker_japanese.rb#L13

**Comment by denvazh** [comment]
Thank you for very detailed description @rbf ! 
Unfortunately, I didn't have notifications enabled for this repository so it took a while before I could actually act upon it. Interestingly, I found this error when I tried to update to the most recent library, created fix and then noticed there was already issue for it 😄

**Comment by rbf** [comment]
Thanks for the reply and for the fix, @denvazh !
